name: Package vsix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Agent
        run: |
          git config --global user.name 'Package Bot'
          git config --global user.email 'Package-bot@users.noreply.github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package
        run: vsce package -o "code-annotation.vsix"

      - name: Commit file
        run: |
          git add code-annotation.vsix
          git commit -nm "Updated vsix package"
          git push
